### ISSUE TITLE
Support Drupal Contrib Security Updates

### ISSUE THREAD

**Issue by Alexander-Cairns** [eiriksm/cosy-composer#247]
Since cozy-composer uses [FriendsOfPHP/security-advisories](https://github.com/FriendsOfPHP/security-advisories) as a source for security advisories and they have decided to [not support Drupal contrib modules](https://github.com/FriendsOfPHP/security-advisories/issues/373#issuecomment-467551775), cozy-composer does not currently them either. Would it be possible to add support for Drupal contrib security advisories? It should be possible to use the same API used by [drupal-comoposer/drupal-security-advisories](https://github.com/drupal-composer/drupal-security-advisories/blob/main/build/build-composer-json.php) to build the list of advisories.

**Comment by Alexander-Cairns** [comment]
Did not see https://github.com/eiriksm/cosy-composer/blob/master/src/CosyComposer.php#L470 and https://github.com/violinist-dev/drupal-contrib-sa/ looks like it's just missing the latest SAs.

**Comment by Alexander-Cairns** [comment]
Pr to add the missing SAs https://github.com/violinist-dev/drupal-contrib-sa/pull/394

**Comment by eiriksm** [comment]
Thanks so much!

The person who added the Drupal contrib SAs was me, so I know this all too well :)

Even more information here: https://medium.com/@violinistdevio/violinist-io-now-supports-security-advisories-from-drupal-contrib-modules-a6a140d8d07c
