### ISSUE TITLE
PRs getting closed when updating multiple branches

### ISSUE THREAD

**Issue by Alexander-Cairns** [eiriksm/cosy-composer#264]
When using violinist to update multiple branches, it can end up closing the current PR in the wrong branch as if it was an outdated PR.

### Example

Suppose Violinist is used to maintain a project with a `main` branch that is at v2 and a `v1` branch for maintaining the old version. Let the `main` branch have no `branch_prefix`and the `v1` have a `branch_prefix` of `v1-`.

If both branches have a module called `mymod` at version 1 that has an update to version 2, the following PRs will be created. `main <- mymod12` and `v1 <- v1-mymod12`.

If `v1 <- v1-mymod12` exists when Violinist runs on the main branch it will be closed as if it is an outdated PR. This seems to be because in `closeOutdatedPrsForPackage` Violinist will "match" against the `v1` branch PR since the `$branch_name_prefix = "mymod1"` is a sub-string of `v1-mymod12` and will be treated as if was it was a PR for the main branch.

https://github.com/eiriksm/cosy-composer/blob/ad547a85c973e96f983412bba295556d26bd0185/src/CosyComposer.php#L538-L571

### Workaround
I have mitigated the issue by having a prefix on all branches.

**Comment by eiriksm** [comment]
Great point!

I'm not sure how common it is to use it like you are using it, but it's certainly a bug!

Thanks for the report, and for the workaround. Let's hope it's not needed for too long 🙂

**Comment by eiriksm** [comment]
This should now be fixed with #265 , which in turn will probaby be rolled out to all workers within a day.

Heopfully that means you don't need the workaround going forward.

Thanks again for reporting this
